name:                 BootstrapValidator
highlighter:          pygments
relative_permalinks:  false

source:               .
destination:          ../bootstrapvalidator.com
markdown:             kramdown
exclude:              ['node_modules', '*.less']
url:                  http://bootstrapvalidator.com/
paginate:             5
permalink:            /news/:title/
timezone:             Asia/Ho_Chi_Minh

# Custom variables
# not defined by Jekyll
current_version:      0.5.2
released_date:        2014.09.25
github_watchers:      980
github_forks:         382
github_downloads:     43600
twitter_followers:    159
download:
  dist:               https://github.com/nghuuphuoc/bootstrapvalidator/releases/download/v0.5.2/bootstrapvalidator-dist-0.5.2.zip
  tag:                https://github.com/nghuuphuoc/bootstrapvalidator/archive/v0.5.2.zip
repository:
  source:             https://github.com/nghuuphuoc/bootstrapvalidator
  docs:               https://github.com/nghuuphuoc/bootstrapvalidator/gh-pages
  docs_edit:          https://github.com/nghuuphuoc/bootstrapvalidator/edit/docs
ga_code:              UA-44786951-2
jquery_plugin_url:    http://plugins.jquery.com/bootstrapValidator
disqus:               bootstrapvalidator